### ISSUE TITLE
Make sure that clocks are synchronized via NTP

### ISSUE THREAD

**Issue by cason** [cometbft/qa-infra#48]
We need to confirm:

- [ ] Whether there is a NTP client/service installed in the images
- [ ] Whether the NTP service is enabled, and the synchronization interval is good enough
- [ ] Whether firewall rules or network setup might be interfering with NTP synchronization

**Comment by lasarojc** [comment]
Shall we close this?

**Comment by hvanz** [comment]
We have manually confirmed than NTP is now working as expected.
